// Jenkinsfile
pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/dineshsiripurapu/chatgpt.git'
                
            }
        }
        
        stage('Build') {
            steps {
                script {
                    docker.withRegistry('https://registry.example.com', 'dckr_pat_gqAbQzWrdlgRmo8oH5TybcIwEgg') {
                        def customImageTag = "my-docker-image:${env.BUILD_NUMBER}"
                        docker.build(customImageTag, '.')
                    }
                }
            }
        }
        
        stage('Push') {
            steps {
                script {
                    docker.withRegistry('https://registry.example.com', 'docker-credentials-id') {
                        def customImageTag = "my-docker-image:${env.BUILD_NUMBER}"
                        docker.image(customImageTag).push()
                    }
                }
            }
        }
    }
}
